puts "Jota".object_id
puts "Jota".object_id
puts "Jota".object_id
puts "Jota".object_id
puts "Jota".object_id
puts "================"
puts :Jota.object_id
puts :Jota.object_id
puts :Jota.object_id
puts :Jota.object_id
puts :Jota.object_id
puts :Jota.object_id